### ISSUE TITLE
[Error: ENOENT: no such file or directory, open 'C:\Users\Игровой\Desktop\тг раб отающий боты\casino322bot-master\token'] {

### ISSUE THREAD

**Issue by axuenno223** [AlexSolari/casino322bot#1]
[Error: ENOENT: no such file or directory, open 'C:\Users\Игровой\Desktop\тг раб
отающий боты\casino322bot-master\token'] {

**Comment by axuenno223** [comment]
ошибка какая то про токена

**Comment by AlexSolari** [comment]
В папке с ботом должен лежать файл с названием **token** и твоим токеном бота.
